### ISSUE TITLE
[Bug] WebSocker client is not working.

### ISSUE THREAD

**Issue by fjpanag** [thingsboard/tbmq#116]
**Describe the bug**
I just upgraded to v1.3.0, and I am trying out the new WebSockets client.

Unfortuneatelly, it is not working.  
I click on the "Connect" button, it gets grayed out, and nothing is happening.

I have verified that the server configuration is correct:
* I checked the open ports in docker compose, firewalls etc.
* I checked that I can connect to the WebSockets port (8084) with telnet.
* I checked in the UI that WebSockets support is enabled.
* **I checked that I can properly connect to the broker using another client, with the exact same credentials and through WebSockets specifically.**

It seems that only the embedded client is not working.

**Your Server Environment**
* Deployment: Docker
* TBMQ version: v1.3.0
* OS name and version: Rocky 9

**Your Client Environment**
**Desktop:**
* OS: Fedora 39
* Browser: Firefox
* Version: 124.0.2

**To Reproduce**

1. Ensure that the connection details / credentials are correct.
2. Press the "Connect" button.

**Expected behavior**
I would expect the client to connect. Or at least throw a meaningful error in case something is wrong.

**Screenshots**
![image](https://github.com/thingsboard/tbmq/assets/46975045/cdd65fee-394e-4ac9-9012-a2ea60d11f38)

*Notice how the "Connect" button is grayed-out, but also the client states "Disconnected".*

**Comment by fjpanag** [comment]
Hello @dmytro-landiak 

> Could you please share with me the docker-compose file that you are using?

Here you are:

```
version: "3.0"
services:
  postgres:
    restart: always
    image: "postgres:15"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: thingsboard_mqtt_broker
      POSTGRES_PASSWORD: postgres
    volumes:
      - tbmq-postgres-data:/var/lib/postgresql/data
  kafka:
    restart: always
    image: "bitnami/kafka:3.5.1"
    ports:
      - "9092"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - tbmq-kafka-data:/bitnami/kafka
  tbmq:
    restart: always
    image: "thingsboard/tbmq:1.3.0"
    depends_on:
      - postgres
      - kafka
    ports:
      - "8083:8083"
      - "1883:1883"
      - "8084:8084"
      - "8883:8883"
    environment:
      TB_SERVICE_ID: tbmq
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard_mqtt_broker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      TB_KAFKA_SERVERS: kafka:9092
      SECURITY_MQTT_BASIC_ENABLED: "true"
      SECURITY_MQTT_SSL_ENABLED: "true"
      LISTENER_SSL_ENABLED: "true"
      LISTENER_SSL_CREDENTIALS_TYPE: "PEM"
      LISTENER_SSL_PEM_CERT: "/data/fullchain.pem"
      LISTENER_SSL_PEM_KEY: "/data/privkey.pem"
      JWT_TOKEN_ISSUER: "example.gr"
      SWAGGER_CONTACT_NAME: "Example"
      SWAGGER_CONTACT_URL: "https://example.gr"
      SWAGGER_CONTACT_EMAIL: "info@example.gr"
    volumes:
      - tbmq-logs:/var/log/thingsboard-mqtt-broker
      - tbmq-data:/data

volumes:
  tbmq-postgres-data:
    external: true
  tbmq-kafka-data:
    external: true
  tbmq-logs:
    external: true
  tbmq-data:
    external: true

```

---

> Additionally, I see you are trying to connect the WS Default Connection. Have you changed any of the configurations of this connection (e.g. Connection Details/Advanced Settings/Last WIll)? If yes, please send me the screenshots of the configuration.

I have only changed the broker address from `localhost` to the actual broker URL.

Nevertheless, here are some screenshots of the configuration:

![Screenshot from 2024-04-17 11-57-33](https://github.com/thingsboard/tbmq/assets/46975045/517d8029-f745-4b87-8de0-d005cf7a074c)

![Screenshot from 2024-04-17 11-57-39](https://github.com/thingsboard/tbmq/assets/46975045/75a26bab-fd77-4e5b-a44c-bf2cd010bc3e)

![Screenshot from 2024-04-17 11-57-43](https://github.com/thingsboard/tbmq/assets/46975045/55a26360-e974-4f9e-bd92-5f1eb761a0ad)

![Screenshot from 2024-04-17 11-57-46](https://github.com/thingsboard/tbmq/assets/46975045/63c3ccdb-6c8f-4e4b-ab8e-c847b4b17e59)

----

> Do you have a deployment to which I could get access (UI/ssh)? This would help a lot in the investigation.

Unfortunately, this is not possible at the moment.

This is a production server, and we cannot share credentials for security reasons.
